I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 33, in script
    e "I've created a new Ren'Py game."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 33, in script
    e "I've created a new Ren'Py game."
  File "/Users/isaacadel/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/isaacadel/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Brouillon 1.0
Tue Mar 21 14:42:07 2023
